const AUTH = {
  AUTH_INIT: "AUTH_INIT",
  AUTH_START: "AUTH_START",
  AUTH_SUCCESS: "AUTH_SUCCESS",
  AUTH_FAIL: "AUTH_FAIL",
  AUTH_LOGOUT: "AUTH_LOGOUT",
  AUTH_CHECK_STATE: "AUTH_CHECK_STATE"
};

export { AUTH };