const AUTH = {
  AUTH_INIT: "AUTH_INIT",
  AUTH_START: "AUTH_START",
  AUTH_SUCCESS: "AUTH_SUCCESS",
  AUTH_FAIL: "AUTH_FAIL",
  AUTH_LOGOUT: "AUTH_LOGOUT",
  AUTH_CHECK_STATE: "AUTH_CHECK_STATE"
};

const CHAT = {
  CHAT_FETCH_INIT: "CHAT_FETCH_INIT",
  CHAT_FETCH_ROOMS: "CHAT_FETCH_ROOMS",
  CHAT_SET_ROOMS: "CHAT_SET_ROOMS",
  CHAT_FETCH_FAIL: "CHAT_FETCH_FAIL",
  CHAT_FETCH_MESSAGES_INIT: "CHAT_FETCH_MESSAGES",
  CHAT_FETCH_MESSAGES_START: "CHAT_FETCH_MESSAGES_START",
  CHAT_SET_MESSAGES: "CHAT_SET_MESSAGES",
  CHAT_FETCH_MESSAGES_END: "CHAT_FETCH_MESSAGES_END",
  CHAT_SEND_MESSAGE_INIT: "CHAT_SEND_MESSAGE_INIT",
  CHAT_SET_MESSAGE_REALTIME: "CHAT_SET_MESSAGE_REALTIME",
  CHAT_SET_USERS_STATUS: "CHAT_SET_USERS_STATUS",
  CHAT_AUTH_CLOSE: "CHAT_AUTH_CLOSE"
};

export { AUTH, CHAT };